spring:
  datasource: # configurações do banco de dados usando o H2
    url: jdbc:h2:mem:sbjb2023 # nome do banco: Santander Bootcamp Java Backend 2023
    username: sbjb2023 # usuário
    password: # sem senha
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false